---
- name: Set macOS defaults
  include_role:
    name: feffi.macos-defaults
  vars:
    macos_defaults:
      defaults:
        - { domain: "com.apple.TimeMachine", key: "DoNotOfferNewDisksForBackup", type: "boolean", value: "{{ macos_timemachine.prompt_new }}", description: "Prevent Time Machine from prompting to use new hard drives as backup volume" }

- name: "Disable Time Machine"
  become: true
  command: "tmutil disable"
  when: not macos_timemachine.enabled
  changed_when: false

- name: "Enable Time Machine"
  become: true
  command: "tmutil enable"
  when: macos_timemachine.enabled
  changed_when: false
